version: '3.9'
services:
  debezium-server:
    image: debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8080:8080"
    volumes:
      - ../../../../gcp-credentials/house-212104-pubsub-publisher.json:/tmp/credentials/service-account.json
      - ./conf:/debezium/conf
